services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bifi
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#    ports:           # Only for local debugging
#      - "5432:5432"

  session-db:
    image: redis:7.4.2
    restart: unless-stopped
#    ports:           # Only for local debugging
#      - "6379:6379"

  app:
    build: .
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bifi
      - REDIS_URL=redis://session-db:6379
      - SESSION_SECRET=changemetorandomstring
    depends_on:
      - db
    ports:
      - "5000:5000"

volumes:
  pgdata:
